# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter',
            new_name='chapter_text',
        ),
    ]
