# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20170704_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='first_fan',
            field=models.CharField(choices=[('CVG', 'جسور والجميلة'), ('KVS', 'ليث ونورا'), ('KG', 'عودة مهند'), ('Ezel', 'إيزل'), ('AM', 'العشق الممنوع'), ('MH', 'ميرنا وخليل'), ('GS', 'نور')], default=('KVS', 'ليث ونورا'), max_length=250),
        ),
    ]
