# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20170704_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='first_fan',
        ),
        migrations.RemoveField(
            model_name='story',
            name='second_fan',
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
