# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20170705_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
