# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20170706_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(default='', max_length=50, null=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500, null=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='stories.Story'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.CharField(default='guest', max_length=50),
        ),
    ]
