# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_story_story_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_cover',
            field=models.FileField(upload_to='/photos'),
        ),
    ]
