# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_auto_20170707_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_cover',
            field=models.FileField(upload_to=''),
        ),
    ]
