# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20170707_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='isCross',
        ),
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
    ]
